FROM openjdk:17

WORKDIR ~/

COPY . .

ENTRYPOINT [ \
    "java", \
    "-Xms4g", "-Xmx8g", \
    "--add-opens", "java.base/java.lang=ALL-UNNAMED", \
    "--add-opens", "java.base/java.lang.ref=ALL-UNNAMED", \
    "--add-opens", "java.base/java.lang.reflect=ALL-UNNAMED", \
    "--add-opens", "java.base/java.nio=ALL-UNNAMED", \
    "--add-opens", "java.base/java.io=ALL-UNNAMED", \
    "--add-opens", "java.base/java.time=ALL-UNNAMED", \
    "--add-opens", "java.base/java.util=ALL-UNNAMED", \
    "--add-opens", "java.base/java.util.concurrent=ALL-UNNAMED", \
    "--add-opens", "java.base/jdk.internal.loader=ALL-UNNAMED", \
    "--add-opens", "java.base/jdk.internal.ref=ALL-UNNAMED", \
    "--add-opens", "java.base/sun.net.www.protocol.http=ALL-UNNAMED", \
    "--add-opens", "java.base/sun.nio.ch=ALL-UNNAMED", \
    "-Dlogback.configurationFile=config/logback.xml", \
    "-jar", "./app.jar" \
]
